config/routes.rb
Rails.application.routes.draw do

  get 'reservations/index'
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'home#top'

  resources :users, only: [:index,:show,:update] do
    member do
      get 'profile'
      get 'profile_edit'

    end
  end
  resources :rooms do
    member do
      get 'own'
    end
  end

  resources :reservations do
    member do
      post 'confirm'
      get 'confirm'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記

  #roomモデルに関連付け
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy
  #画像アップロード用
  mount_uploader :icon, IconUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  #コメント解除
  #before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected

  #追記
  # def update_resource(resource, params)
    # resource.update_without_password(params)
  # end

  # def configure_account_update_params
    # devise_parameter_sanitizer.permit(:account_update,
      # keys: [:email, :encrypted_password, :reset_password_token, :reset_password_sent_at])
  # end

  # アカウント編集後、プロフィール画面に移動する
  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :sign_in_required, only: [:show ,:own ,:update]

  def index
    @users = User.all
    @rooms = Room.all
  end

  def show
    @user = User.find(params[:id])
  end

  def profile_edit
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "登録しました"
      redirect_to :profile_user
    else
      flash.now[:alert] = "登録に失敗しました"
      render :profile_edit , status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :icon,
        :name,
        :profile,
        :remove_icon
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ユーザー一覧</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>
<h3>投稿一覧</h3>

  <%= link_to 'サインアップ', new_user_registration_path %>

app/views/users/profile.html.erb
<section class="container UserSection">
    <h2>設定</h2>
    <div class="UserContainer">
        <ul class="SideNavigation">
            <li class="SideNavigation__item "><%= link_to "アカウント", user_path(current_user) %>  </li>
            <li class="SideNavigation__item active"><%= link_to "プロフィール", profile_user_path(current_user) %> </li>
        </ul>
        <div class="AccountInformation">
            <div class="AccountInformation__header">
                <h3>プロフィール</h3>
                <%= link_to "編集",profile_edit_user_path(current_user),class: "AccountInformation__link" %>
            </div>

            <div class="AccountInformation__input-group">
                <label class="AccountInformation__label" for="image">アイコン画像</label>
                <p class="AccountInformation__value AccountInformation__value--image">
                    <% if @user.icon? %>
                        <%= image_tag @user.icon.url , class: "user-icon"%>
                    <% else %>
                        <%= image_tag("default-icon.png") %>
                    <% end %>
                </p>
            </div>

            <div class="AccountInformation__input-group">
                <label class="AccountInformation__label" for="name">名前</label>
                <p class="AccountInformation__value"><%= @user.name %></p>
            </div>

            <div class="AccountInformation__input-group">
                <label class="AccountInformation__label" for="introduction">自己紹介</label>
                <p class="AccountInformation__value"><%= @user.profile %></p>
            </div>
        </div>
    </div>
</section>

app/views/users/profile_edit.html.erb
<section class="container UserSection">
    <h2>設定</h2>
    <div class="UserContainer">
        <ul class="SideNavigation">
            <li class="SideNavigation__item "><%= link_to "アカウント", user_path(current_user) %>  </li>
            <li class="SideNavigation__item active"><%= link_to "プロフィール", profile_user_path(current_user) %> </li>
        </ul>
        <div class="AccountInformation">
            <div class="AccountInformation__header">
                <h3>プロフィール</h3>
            </div>

            <%= render "shared/validate", obj: @user %>

            <%= form_with model: @user , local: true do |f| %>
                <div class="FileUploadArea AccountInformation__input-group">
                    <%= f.label :プロフィール画像 ,class:"AccountInformation__label"%><br/>
                    <p class="FileUploadArea__input-group">
                        <% if @user.icon? %>
                            <%= image_tag @user.icon.thumb.url, class: "user-icon FileUploadArea__image" %>
                        <% else %>
                            <%= image_tag "default-icon.png", alt: "user-icon", size: "100", class: "user-icon" %>
                        <% end %>
                        <br>
                        <div class="icon-upload">
                            <%= f.file_field :icon %>
                            <div class="form-check">
                                <%= f.check_box :remove_icon ,class:"form-check-input",id:"flexCheckDefault"%>
                                <%= f.label :画像を削除する ,class:"form-check-label" ,for:"flexCheckDefault"%>
                            </div>
                        </div>
                    </p>
                </div>

                <div class="AccountInformation__input-group">
                    <%= f.label :ユーザーネーム ,class:"AccountInformation__label" %><br />
                    <div class="AccountInformation__input-wrapper">
                        <%= f.text_field :name, autofocus: true, autocomplete: "name" ,class:"AccountInformation__input" ,placeholder:"名前を入力"%>
                    </div>
                </div>

                <div class="AccountInformation__input-group">
                    <%= f.label :自己紹介 ,class:"AccountInformation__label"%><br />
                    <div class="AccountInformation__input-wrapper">
                        <%= f.text_area :profile, autofocus: true, autocomplete: "profile" ,class:"AccountInformation__input" ,placeholder:"自己紹介を入力"%>
                    </div>
                </div>

                <div class="actions AccountInformation__buttons">
                    <%= link_to "戻る", :back ,class:"btn AccountInformation__button AccountInformation__button--secondary"%>
                    <%= f.submit "更新" ,class:"btn AccountInformation__button AccountInformation__button--primary"%>
                </div>
            <% end %>

        </div>
    </div>
</section>

app/views/users/show.html.erb
<section class="container UserSection">
    <h2>設定</h2>
    <div class="UserContainer">
        <ul class="SideNavigation">
            <li class="SideNavigation__item active"><%= link_to "アカウント", user_path(current_user) %>  </li>
            <li class="SideNavigation__item "><%= link_to "プロフィール", profile_user_path(current_user) %> </li>
        </ul>
        <div class="AccountInformation">
            <div class="AccountInformation__header">
                <h3>アカウント</h3>
                <%= link_to "編集",edit_user_registration_path,class: "AccountInformation__link" %>
            </div>

            <div class="AccountInformation__input-group">
                <label class="AccountInformation__label" for="email">メールアドレス</label>
                <p class="AccountInformation__value"><%= @user.email %></p>
            </div>

            <div class="AccountInformation__input-group">
                <label class="AccountInformation__label" for="password">パスワード</label>
                <p class="AccountInformation__value">*********</p>
            </div>
        </div>
    </div>
</section>