config/routes.rb
Rails.application.routes.draw do

  get 'reservations/index'
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'home#top'

  resources :users, only: [:index,:show,:update] do
    member do
      get 'profile'
      get 'profile_edit'

    end
  end
  resources :rooms do
    member do
      get 'own'
    end
  end

  resources :reservations do
    member do
      post 'confirm'
      get 'confirm'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/top.html.erb
<div class="firstview">
    <section class="main-container">
        <h1 class="firstview-title">旅をしよう</h1>
        <div class="FirstViewSearch">
            <%= search_form_for @q  do |f| %>
                <%= f.search_field :address_cont , placeholder: 'エリア名', class:"form-control FirstViewSearch__input"%>
                <%= f.submit :検索 ,class:"btn FirstViewSearch__button"%>
            <% end %>
        </div>
    </section>
</div>

<div class="container">
    <section class="RecommendAreaSection">
        <h2 class="RecommendAreaSection__title">おすすめのエリア</h2>

        <div class="RecommendAreas">
            <%= link_to rooms_path(q: {address_cont: "東京"}),class:"RecommendArea RecommendArea--tokyo" do %>
                <span class="RecommendArea__name RecommendArea__name--ja">東京</span>
                <span class="RecommendArea__name RecommendArea__name--en">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"></path>
                    </svg>
                    Tokyo
                </span>
            <%end%>

            <%= link_to rooms_path(q: {address_cont: "大阪"}) ,class:"RecommendArea RecommendArea--osaka" do%>
                <span class="RecommendArea__name RecommendArea__name--ja">大阪</span>
                <span class="RecommendArea__name RecommendArea__name--en">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"></path>
                    </svg>
                    Osaka
                </span>
            <%end%>

            <%= link_to rooms_path(q: {address_cont: "京都"}) ,class:"RecommendArea RecommendArea--kyoto" do%>
                <span class="RecommendArea__name RecommendArea__name--ja">京都</span>
                <span class="RecommendArea__name RecommendArea__name--en">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"></path>
                    </svg>
                    Kyoto
                </span>
            <%end%>

            <%= link_to rooms_path(q: {address_cont: "札幌"}) ,class:"RecommendArea RecommendArea--sapporo" do%>
                <span class="RecommendArea__name RecommendArea__name--ja">札幌</span>
                <span class="RecommendArea__name RecommendArea__name--en">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"></path>
                    </svg>
                    Sapopro
                </span>
            <%end%>
        </div>
    </section>
</div>