config/routes.rb
Rails.application.routes.draw do

  get 'reservations/index'
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'home#top'

  resources :users, only: [:index,:show,:update] do
    member do
      get 'profile'
      get 'profile_edit'

    end
  end
  resources :rooms do
    member do
      get 'own'
    end
  end

  resources :reservations do
    member do
      post 'confirm'
      get 'confirm'
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
    #userモデルに関連付け
    belongs_to :user
    has_many :reservations, dependent: :destroy
    #画像アップロード用
    mount_uploader :image, ImageUploader

    validates :name,:introduction,:priice,:address, presence: true
    validates :priice, numericality: true
    validates :priice, numericality: {only_integer: true, greater_than_or_equal_to: 0}

    def self.ransackable_attributes(auth_object = nil)
        ["address", "name","introduction"]
    end

    #よくわからないけど必要
    def self.ransackable_associations(auth_object = nil)
        ["user"]
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id #deviseのメソッドを使って「ログインしている自分のid」を代入
      if @room.save
        flash[:notice] = "投稿しました"
        redirect_to @room
      else
        flash.now[:alert] = "投稿に失敗しました"
        render "new"
      end
  end

  def show
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    @room = Room.find(params[:id])
    @user = @room.user
    @reservation=Reservation.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "投稿しました"
      redirect_to @room
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :edit , status: :unprocessable_entity
    end
  end

  def destroy
    @room = Room.find(params[:id])
      @room.destroy
      flash[:notice] = "ユーザーを削除しました"
      redirect_back(fallback_location: root_path)
  end

  def own
    @user = User.find(params[:id])
    @rooms = @user.rooms
  end

  private
    def room_params
      params.require(:room).permit(
        :image,
        :name,
        :introduction,
        :priice,
        :address,
        :user_id
      )
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="main-container">
    <section class="FormContainer">
        <h2>施設情報の編集</h2>

        <%= render "shared/validate", obj: @room %>

        <%= form_with model: @room , local: true do |f| %>
            <div class="RoomsForm__input-group">
                <%= f.label :name ,"施設名" ,class:"form-label RoomsForm__label Form__label--required"%>
                <div class="RoomsForm__input">
                    <%= f.text_field :name ,class:"form-control" ,id:"name" ,placeholder:"ルーム名を入力"%>
                </div>
            </div>

            <div class="RoomsForm__input-group">
                <%= f.label :introduction ,"施設詳細" ,class:"form-label RoomsForm__label Form__label--required"%>
                <div class="RoomsForm__input">
                    <%= f.text_area :introduction , class:"form-control" ,id:"introduction",rows:"5" , placeholder:"施設詳細を入力"%>
                </div>
            </div>

            <div class="RoomsForm__input-group">
                <%= f.label :priice ,"料金" ,class:"form-label RoomsForm__label Form__label--required"%>
                <div class="RoomsForm__input">
                    <%= f.number_field :priice , class:"form-control" ,id:"priice",placeholder:"一日あたりの料金を入力"%>
                </div>
            </div>

            <div class="RoomsForm__input-group">
                <%= f.label :address ,"住所" ,class:"form-label RoomsForm__label Form__label--required"%>
                <div class="RoomsForm__input">
                    <%= f.text_field :address ,class:"form-control" ,id:"address" ,placeholder:"住所を入力"%>
                </div>
            </div>

            <div class="RoomsForm__input-group FileUploadArea">
                <%= f.label :image ,"施設写真" ,class:"RoomsForm__label"%>
                <div class=" RoomsForm__input FileUploadArea__input-group">
                    <%= f.file_field :image ,class:"form-control" ,id:"image" %>
                </div>
            </div>

            <%= f.submit "保存" ,class:"btn RoomsForm__button RoomsForm__button--submit"%>
        <% end %>
        <%= link_to "戻る", :back ,class:"btn RoomsForm__button RoomsForm__button--cancel"%>
    </section>
</div>

app/views/rooms/index.html.erb
<div class="SearchRoomsFormContainer">
    <%= search_form_for(@q, html: {class:"SearchRoomsForm"} ) do |f| %>
        <div class="SearchRoomsForm__input-group SearchRoomsForm__input-group--area">
            <%= f.search_field :address_cont , placeholder: 'エリア名' , class:"form-control SearchRoomsForm__input"%>
        </div>

        <div class="SearchRoomsForm__input-group SearchRoomsForm__input-group--keyword">
            <%= f.search_field :introduction_or_name_cont , placeholder: 'キーワード名を入力' , class:"form-control SearchRoomsForm__input"%>
        </div>

        <%= f.submit:検索 ,class:"SearchRoomsForm__button" %>
    <% end %>
</div>

<div class="container RoomsContainer">
    <p class="RoomsContainer__result"><%= "#{@rooms.count}件が見つかりました。" %></p>

    <ul class="RoomList ">
        <% @rooms.each do |room| %>
            <li class="Room">
                <%= image_tag room.image.url ,class:"Room__image"%>
                <div class="RoomBodyWrapper">
                    <p class="Room__name"><%= room.name %></p>

                    <p class="Room__address"><%= room.address %></p>

                    <p class="Room__content"><%= room.introduction %></p>

                    <div class="RoomFooter">
                        <p class="Room__price">¥<%= room.priice %>~</p>
                        <%=link_to "詳細はこちら", room_path(room.id) ,class:"Room__link"%>
                    </div>
                </div>
            </li>
        <% end %>
    </ul>
</div>

app/views/rooms/new.html.erb
<div class="main-container">
    <section class="FormContainer">
        <h2>施設登録</h2>

        <%= render "shared/validate", obj: @room %>

        <%= form_with model: @room , local: true do |f| %>
            <div class="RoomsForm__input-group">
                <%= f.label :name ,"施設名" ,class:"form-label RoomsForm__label Form__label--required"%>
                <div class="RoomsForm__input">
                    <%= f.text_field :name ,class:"form-control" ,id:"name" ,placeholder:"ルーム名を入力"%>
                </div>
            </div>

            <div class="RoomsForm__input-group">
                <%= f.label :introduction ,"施設詳細" ,class:"form-label RoomsForm__label Form__label--required"%>
                <div class="RoomsForm__input">
                    <%= f.text_area :introduction , class:"form-control" ,id:"introduction",rows:"5" , placeholder:"施設詳細を入力"%>
                </div>
            </div>

            <div class="RoomsForm__input-group">
                <%= f.label :priice ,"料金" ,class:"form-label RoomsForm__label Form__label--required"%>
                <div class="RoomsForm__input">
                    <%= f.number_field :priice , class:"form-control" ,id:"priice",placeholder:"一日あたりの料金を入力"%>
                </div>
            </div>

            <div class="RoomsForm__input-group">
                <%= f.label :address ,"住所" ,class:"form-label RoomsForm__label Form__label--required"%>
                <div class="RoomsForm__input">
                    <%= f.text_field :address ,class:"form-control" ,id:"address" ,placeholder:"住所を入力"%>
                </div>
            </div>

            <div class="RoomsForm__input-group FileUploadArea">
                <%= f.label :image ,"施設写真" ,class:"RoomsForm__label"%>
                <div class=" RoomsForm__input FileUploadArea__input-group">
                    <%= f.file_field :image ,class:"form-control" ,id:"image" %>
                </div>
            </div>

            <%= f.submit "保存" ,class:"btn RoomsForm__button RoomsForm__button--submit"%>
        <% end %>
        <%= link_to "戻る", :back ,class:"btn RoomsForm__button RoomsForm__button--cancel"%>
    </section>
</div>

app/views/rooms/own.html.erb
<section class="container OwnRoomsContainer">
    <h2>登録済み一覧</h2>

    <div class="table-responsive">
        <table class="table align-middle OwnRoomsTable">
            <thead>
                <tr>
                    <th>画像</th>
                    <th>施設名</th>
                    <th>施設詳細</th>
                    <th>料金</th>
                    <th>作成日</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <% @rooms.each do |room| %>
                    <tr>
                        <td>
                            <%= image_tag room.image.url ,class:"RoomDetails__image"%>
                        </td>

                        <td>
                            <%=link_to room.name, room_path(room.id) %>
                        </td>

                        <td>
                            <%= room.introduction %>
                        </td>

                        <td class="text-nowrap">
                            <p>¥<%= room.priice %>/日</p>
                        </td>

                        <td class="text-nowrap">
                            <%=l room.updated_at.to_date %>
                        </td>

                        <td>
                            <div class="dropdown">
                                <div class="d-flex align-items-center justify-content-center" id="dropdown-button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <%= image_tag "kebab.jpg", alt: "Rails icon", id: "assets", class: "image", width: "20px" %>
                                </div>

                                <ul class="dropdown-menu DropdownMenu" aria-labelledby="dropdown-button">
                                    <li class="DropdownMenu__item">
                                        <%= link_to "編集",edit_room_path(room) %>
                                    </li>

                                    <li class="DropdownMenu__item DropdownMenu__item--danger">
                                        <%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</section>

app/views/rooms/show.html.erb
<div class="SearchRoomsFormContainer">
    <%= search_form_for(@q, html: {class:"SearchRoomsForm"} ) do |f| %>
        <div class="SearchRoomsForm__input-group SearchRoomsForm__input-group--area">
            <%= f.search_field :address_cont , placeholder: 'エリア名' , class:"form-control SearchRoomsForm__input"%>
        </div>

        <div class="SearchRoomsForm__input-group SearchRoomsForm__input-group--keyword">
            <%= f.search_field :introduction_or_name_cont , placeholder: 'キーワード名を入力' , class:"form-control SearchRoomsForm__input"%>
        </div>

        <%= f.submit:検索 ,class:"SearchRoomsForm__button" %>
    <% end %>
</div>

<div class="container RoomDetailsContainer">

    <%= flash[:danger] %>
    <%= render "shared/validate", obj: @reservation %>

    <div class="RoomDetailsHeader">
        <%= link_to "戻る", 'javascript:history.back()' ,class:" AccountInformation__button  RoomDetailsHeader__link"%>

        <% if user_signed_in? %>
            <% if @room.user_id === current_user.id %>
                <%= link_to "編集",edit_room_path,class: "AccountInformation__link RoomDetailsHeader__link" %>
            <%end%>
        <%end%>
    </div>

    <div class="RoomDetails">
        <%= image_tag @room.image.url ,class:"RoomDetails__image"%>

        <div class="RoomDetailsBody">

            <div class="RoomDetailsBody__name-and-price">
                <p class="RoomDetails__name"><%= @room.name %></p>
                <p class="RoomDetails__price">¥<%= @room.priice %></p>
            </div>

            <p class="RoomDetails__address"><%= @room.address %></p>
            <p class="RoomDetails__content"><%= @room.introduction %></p>

            <div class="ReservationForm">
                <%= form_with model:@reservation, url:confirm_reservation_path , local: true do |f| %>

                    <%= f.hidden_field :room_id, value: @room.id %>

                    <div class="ReservationForm__input-container">
                        <div class="ReservationForm__input-group">
                            <%= f.label :checkin, "チェックイン" %>

                            <div class="ReservationForm__input ReservationForm__input--date">
                                <%= f.date_field :checkin , min: Time.zone.now,class:"form-control js-picker" ,placeholder:"---- / -- / --" %>
                            </div>
                        </div>

                        <div class="ReservationForm__input-group">
                            <%= f.label :checkout, "チェックアウト" %>
                                <div class="ReservationForm__input ReservationForm__input--date">
                                    <%= f.date_field :checkout  ,min: Time.zone.now, class:"form-control js-picker" ,placeholder:"---- / -- / --" %>
                                </div>
                        </div>

                        <div class="ReservationForm__input-group ReservationForm__input-group--person-count">
                            <%= f.label :Number_of_people, "人数" %>
                            <%= f.number_field :Number_of_people,class:"form-control ReservationForm__input ReservationForm__input--person-count", placeholder:"0"%>
                            <span>人</span>
                        </div>

                    </div>

                    <% if user_signed_in? %>
                        <%= f.hidden_field :user_id, value: current_user.id %>
                        <%= f.submit:予約する ,class:"btn ReservationForm__button" %>
                    <% else %>
                        <%= link_to "ログイン", new_user_session_path, type: "button",class:"btn ReservationForm__button" %>
                    <%end%>

                <% end %>
            </div>
        </div>
    </div>
</div>